// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetFileContent(arg1:string):Promise<string>;

export function LoadConfig():Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function ScanDirectory(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;
